_BASE_: ctrg.yml

# Visual Extractor
visual_extractor: swin3d_l
feature_size: 96 
pretrain_cnn_file: #
d_vf: 2304 
batch_size: 2


# Output Dir
save_dir: /jhcnas5/nixuefeng/jhcpu5_data_files/CTRG/results
